-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE 
date_format(DATE_OF_BIRTH, '%Y-%m-%d')  LIKE '%-03-%' 
AND GENDER = 'W'
AND NOT TLNO = 'null'
ORDER BY MEMBER_ID ASC;