-- 코드를 입력하세요
# SELECT *
#  FROM ANIMAL_OUTS;
SELECT 
DATE_FORMAT(DATETIME, '%H') AS HOUR,
COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%T') 
BETWEEN '09:00:00' AND '19:59:59'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H');